services:
  code:
    container_name: voice_cloning_finetune
    platform: linux/x86_64
    tty: true
    build:
      context: ..
      dockerfile: docker/.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    working_dir: /home/voice-cloning-finetune
    volumes:
      - ../code:/home/voice-cloning-finetune
      - ../.cache/huggingface:/root/.cache/huggingface